# Generated by Django 3.2.16 on 2025-12-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options'),
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
    ]
